name: tests
on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    run_style_check:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
          - uses: actions/checkout@v2
          - uses: conda-incubator/setup-miniconda@v2
            with:
              activate-environment: AbDes
              environment-file: environment.yml
          - run: |
              pycodestyle $(git ls-files "src/*.py")
              pycodestyle $(git ls-files "test/unit/*.py")

    run_functional_create_AbAg:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
          - uses: actions/checkout@v2
          - uses: conda-incubator/setup-miniconda@v2
            with:
              activate-environment: AbDes
              environment-file: environment.yml
          - run: |
             cd test/functional
             bash test_create_AbAg.sh

    run_unittest_master_utils:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
          - uses: actions/checkout@v2
          - uses: conda-incubator/setup-miniconda@v2
            with:
              activate-environment: AbDes
              environment-file: environment.yml
          - run: |
             cd test/unit
             python -m test_master_utils

    run_unittest_structure_utils:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -l {0}
        steps:
          - uses: actions/checkout@v2
          - uses: conda-incubator/setup-miniconda@v2
            with:
              activate-environment: AbDes
              environment-file: environment.yml
          - run: |
             cd test/unit
             python -m test_structure_utils
